#!/bin/bash

open_env() {
    if [[ -d "${source}/.python" ]]; then
        echo Opening Python Enviroment
        source "${source}/.python/bin/activate"
    else
        echo Making Python Environment
        python3 -m venv "${source}/.python"
        source "${source}/.python/bin/activate"
        python3 -m pip install -r requirements.txt
    fi
}

tidy_env() {
    echo Exiting Python Environment
    deactivate
}

source="${PWD}"
current_dir=$(basename "${source}")
if [[ "${current_dir}" == "tests" ]]; then
    source=$(dirname "${source}")
fi

cd "${source}"
open_env
cd tests
echo Running tests
python3 -m unittest -v -b tests.py
tidy_env
